### ISSUE TITLE
Infinite loop when writing to a pipe closed on the other end

### ISSUE THREAD

**Issue by tsufeki** [recoilphp/react#6]
On linux, using `yield Recoil::write($pipe, $data)` when the other end of the pipe is closed (for example its process has exited) leads to an infinite loop in `ReactApi::write()`.

I found that `stream_select()` marks the stream as ready to write, but `fwrite()` returns `0` (not `false`), and no errors are thrown. See http://php.net/manual/en/function.fwrite.php#96951

I propose the solution [taken by react/stream](https://github.com/reactphp/stream/blob/master/src/WritableResourceStream.php#L132), i.e. check [here](https://github.com/recoilphp/react/blob/master/src/ReactApi.php#L200) for `$bytes === 0` as well. `stream_select()` indicates that it's possible to write at least one byte, so zero can only mean an error condition.

I think this applies to the reference kernel as well.

Thank you.

**Comment by jmalloc** [comment]
Thanks for the report!

**Comment by jmalloc** [comment]
Fixed in `1.0.1` tag. Thanks again for the detailed report :)

**Comment by tsufeki** [comment]
It seems it's a partial fix. This time I've made a PR #8, please check it out.
